// AEOS Adapter: LangGraph JS
// Wraps LangGraph StateGraph.invoke() to emit AEOS-compatible OTel spans.
// Generated by: aeos-sdk generate --adapter langgraph
// For usage: see sdk/CLAUDE.md

export { LangGraphAdapter } from './adapter.js';
