apiVersion: v2
name: aeos-service-REPLACE_ME
description: AEOS Platform — REPLACE_ME service
type: application
version: 0.1.0
appVersion: "0.1.0"
annotations:
  "app.kubernetes.io/part-of": "aeos-platform"
