apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "substrate.fullname" . }}
  labels:
    {{- include "substrate.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
