// AEOS Adapter: Google Vertex AI
// Wraps VertexAI GenerativeModel to emit AEOS-compatible OTel spans automatically.
// Generated by: aeos-sdk generate --adapter vertex
// For usage: see sdk/CLAUDE.md

export { VertexAdapter } from './adapter.js';
