// AEOS Adapter: Human-in-the-loop Workflow
// Models human approval steps and emits AEOS-compatible OTel spans.
// Generated by: aeos-sdk generate --adapter human-workflow
// For usage: see sdk/CLAUDE.md

export { HumanWorkflowAdapter } from './adapter.js';
export type { ApprovalFn, DecisionRequest, DecisionResult } from './adapter.js';
