apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "telemetry.fullname" . }}
  labels:
    {{- include "telemetry.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
