// AEOS Adapter: Claude Cowork
// Processes Claude Cowork OTLP traces and logs and emits AEOS skill-execution
// spans via the AEOS adapter SDK emitter.
//
// Generated by: aeos-sdk generate --adapter cowork
// Pattern transplanted from AITT (fuzebox-intelligence) src/collectors/cowork-otel/

export { CoworkAdapter } from './adapter.js';
export type {
  CoworkAdapterOptions,
  CoworkSkillUrlPattern,
  CoworkSpanInput,
  CoworkLogInput,
} from './adapter.js';
