// AEOS Adapter: OpenAI SDK
// Wraps OpenAI's client to emit AEOS-compatible OTel spans automatically.
// Generated by: aeos-sdk generate --adapter openai
// For usage: see sdk/CLAUDE.md

export { OpenAIAdapter } from './adapter.js';
