apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aeos-substrate
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: aeos-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fuzebox-ai/aeos-platform.git
    targetRevision: HEAD
    path: services/substrate/helm
    helm:
      valueFiles:
        - values.yaml
        - values-non-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: substrate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
