// AEOS Adapter: Salesforce Agentforce
// Wraps the Agentforce AI Assist REST API to emit AEOS-compatible OTel spans.
// Generated by: aeos-sdk generate --adapter agentforce
// For usage: see sdk/CLAUDE.md

export { AgentforceAdapter } from './adapter.js';
export type { AgentforceRequest, AgentforceResponse } from './adapter.js';
