// AEOS Adapter: AWS Bedrock
// Wraps BedrockRuntimeClient to emit AEOS-compatible OTel spans automatically.
// Generated by: aeos-sdk generate --adapter bedrock
// For usage: see sdk/CLAUDE.md

export { BedrockAdapter } from './adapter.js';
