// AEOS Adapter: Anthropic SDK
// Wraps Anthropic's client to emit AEOS-compatible OTel spans automatically.
// Generated by: aeos-sdk generate --target=anthropic
// For usage: see packages/sdk-core/CLAUDE.md

export { AnthropicAeosAdapter } from './adapter.js';
